# travis conf: see `https://travis-ci.org/lemoncloud-io/lemon-hello-api`
language: node_js
sudo: false
node_js:
  - 10
  - 8
install:
    - npm install
script:
    - npm run test
env:
    # codecov token: see `https://codecov.io/gh/lemoncloud-io/lemon-hello-api/settings`
    - CODECOV_TOKEN="0cd44aea-7596-4f0c-b830-110c85fd9d3d"
after_success:
    - ./node_modules/.bin/codecov
deploy:
    # deploy to npm: see `https://www.npmjs.com/package/lemon-hello-api`
    provider: npm
    email: steve@lemoncloud.io
    api_key: c92195ff-1783-491b-b934-701b3be9ebd9

    